version: '3.8'

volumes:
  clickhouse_data:

services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
      # environment:
      # CONFIG_FILE: /etc/rabbitmq/main/rabbitmq.conf
      # RABBITMQ_DEFAULT_PASS: guest
      # RABBITMQ_DEFAULT_USER: guest
    volumes:
      - ./rabbitmq/conf:/etc/rabbitmq/
      - ./rabbitmq/data:/var/lib/rabbitmq
    healthcheck:
      test:
        [ "CMD", "echo", "Awaiting rabbitmq..." ]
      interval: 10s
      timeout: 10s
      retries: 8

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: 'clickhouse'
    hostname: 'clickhouse'
    restart: unless-stopped
    volumes:
      - ./clickhouse/configs:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/configs:/etc/clickhouse-server/users.d/users.xml
      - clickhouse_data:/var/lib/clickhouse/
    ports:
      - "8123:8123"
      - "9000:9000"

  collector:
    hostname: collector
    container_name: 'collector'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env.development
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - clickhouse
